import Head from "next/head";
import { useEffect } from "react";
import { SessionProvider } from "next-auth/react"

/*all css import*/
import "../../styles/main.css";

function MyApp({ Component, 
  pageProps : {session, ...pageProps },
 }) {
  useEffect(() => {
    import("../../public/assets/js/bootstrap.bundle.min.js");
  });
  return (
    <>
      <Head>
        <title>Scooby</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/sm-logo.svg" />
      </Head>
      <SessionProvider session={session}>
        <Component {...pageProps} />
        </SessionProvider>

    </>
  );
}

export default MyApp;
